server:
  port: 8089 # 端口

spring:
  application:
    name: ms-order # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://154.8.177.34:3306/db_imooc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  #rabbitMQ
  rabbitmq:
    host: 154.8.177.34
    port: 5672
    username: guest
    password: guest
    #发送端确认机制
    publisher-confirm-type: correlated
    #发送端返回机制
    publisher-returns: true
  # swagger
  swagger:
    base-package: com.imooc.order
    title: 慕课美食社交食客API接口文档

# Oauth2 客户端信息
oauth2:
  client:
    client-id: appId
    secret: 123456
    grant_type: password
    scope: api

# oauth2 服务地址
service:
  name:
    ms-oauth-server: http://ms-oauth2-server/

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'