server:
  port: 8085 # 端口

spring:
  application:
    name: ms-feeds # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://154.8.177.34:3306/db_imooc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    port: 6379
    host: 154.8.177.34
    timeout: 3000
    password: 123456
    # lettuce 连接池
    lettuce:
      pool:
        max-active: 8 # 最大连接数，默认 8
        max-idle: 8 # 最大空闲连接，默认 8
        min-idle: 0 # 最小空闲连接，默认 0
        max-wait: 1000 # 最大连接阻塞等待时间，单位毫秒，默认 -1
    # 哨兵
    sentinel:
      # 主节点名称
      master: mymaster
      # 主从服务器地址
      nodes: 192.168.10.101:26379,192.168.10.102:26379,192.168.10.103:26379
  #RabbitMQ
  rabbitmq:
    host: 192.168.10.101
    port: 5672
    username: guest
    password: guest
  # Swagger
  swagger:
    base-package: com.imooc.feeds
    title: 慕课美食社交食客API接口文档

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-diners-server: http://ms-diners/
    ms-follow-server: http://ms-follow/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
